import { createFileRoute } from "@tanstack/react-router";
import { ClipboardList, Loader2, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type Log={id:string;action:string;target_type:string;target_label:string|null;details:any;created_at:string;admin_user_id:string};
type Profile={id:string;full_name:string|null};
export const Route=createFileRoute("/learn/manage/audit-log")({component:AuditLog});
function AuditLog(){const[logs,setLogs]=useState<Log[]>([]),[admins,setAdmins]=useState<Profile[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in.");setLoading(false);return}const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me?.role!=="admin"){setError("Only admins can view the activity log.");setLoading(false);return}const[{data:l,error:le},{data:p,error:pe}]=await Promise.all([supabase.from("admin_audit_log").select("id,action,target_type,target_label,details,created_at,admin_user_id").order("created_at",{ascending:false}).limit(500),supabase.from("profiles").select("id,full_name").eq("role","admin")]);if(le||pe)setError(le?.message||pe?.message||"Unable to load activity log.");else{setLogs((l||[]) as Log[]);setAdmins((p||[]) as Profile[])}setLoading(false)}void load()},[]);const filtered=useMemo(()=>logs.filter(l=>`${l.action} ${l.target_type} ${l.target_label||""} ${admins.find(a=>a.id===l.admin_user_id)?.full_name||""}`.toLowerCase().includes(q.toLowerCase())),[logs,admins,q]);if(loading)return <LearnShell><div className="learn-card p-6 text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={18}/>Loading activity...</div></LearnShell>;return <LearnShell><SectionHeader eyebrow="Admin · Security" title="Activity Log" description="A read-only record of important administrative actions."/><div className="learn-card p-4"><div className="relative"><Search className="absolute left-3 top-3 text-slate-500" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search activity" className="w-full rounded-xl border border-white/10 bg-white/5 py-2.5 pl-9 text-sm text-white"/></div><div className="mt-5 space-y-2">{filtered.map(l=><div key={l.id} className="rounded-xl border border-white/8 bg-white/[.03] p-4"><div className="flex gap-3"><div className="mt-0.5 rounded-lg bg-cyan-400/10 p-2"><ClipboardList size={16} className="text-cyan-300"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="font-semibold">{l.action}</span><span className="text-slate-500">·</span><span className="text-slate-400">{l.target_label||l.target_type}</span></div><div className="mt-1 text-xs text-slate-500">{admins.find(a=>a.id===l.admin_user_id)?.full_name||"Admin"} · {new Date(l.created_at).toLocaleString()}</div>{Object.keys(l.details||{}).length>0&&<div className="mt-2 text-xs text-slate-500">{Object.entries(l.details).map(([k,v])=><span key={k} className="mr-3">{k}: {String(v)}</span>)}</div>}</div></div></div>)}{!filtered.length&&<div className="py-10 text-center text-sm text-slate-500">No activity recorded yet.</div>}</div></div></LearnShell>}
