import { createFileRoute } from "@tanstack/react-router";
import { Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/learn/manage/chatrooms")({ component: ChatroomManager });
type Room={id:string;name:string;description:string|null;is_active:boolean;created_at:string};
function ChatroomManager(){const[rooms,setRooms]=useState<Room[]>([]);const[name,setName]=useState("");const[description,setDescription]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
async function load(){setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("You are not signed in.");setLoading(false);return}const{data:p}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(p?.role!=="admin"){setError("Only admins can manage chatrooms.");setLoading(false);return}const{data,error:e}=await supabase.from("chatrooms").select("id,name,description,is_active,created_at").order("created_at",{ascending:true});if(e)setError(e.message);else setRooms((data||[])as Room[]);setLoading(false)}
useEffect(()=>{void load()},[]);async function create(){if(!name.trim()){setError("Chatroom name is required.");return}setSaving(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("You are not signed in.");setSaving(false);return}const{error:e}=await supabase.from("chatrooms").insert({name:name.trim(),description:description.trim()||null,created_by:user.id});if(e)setError(e.message);else{name&&setName("");setDescription("");await load()}setSaving(false)}
async function toggle(r:Room){const{error:e}=await supabase.from("chatrooms").update({is_active:!r.is_active}).eq("id",r.id);if(e)setError(e.message);else await load()}
async function remove(r:Room){if(!window.confirm(`Delete chatroom "${r.name}" and its messages?`))return;const{error:e}=await supabase.from("chatrooms").delete().eq("id",r.id);if(e)setError(e.message);else await load()}
if(loading)return <LearnShell><div className="learn-card p-6 text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={18}/>Loading chatrooms...</div></LearnShell>;
return <LearnShell><SectionHeader eyebrow="Admin · Community" title="Chatrooms" description="Create and manage the community rooms students can join."/><div className="learn-card mb-6 p-6"><div className="grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="text-sm text-slate-300">Chatroom name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Introduce Yourself" className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white"/></label><label className="text-sm text-slate-300">Description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="A place to introduce yourself" className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white"/></label><button type="button" onClick={()=>void create()} disabled={saving} className="learn-primary-button">{saving?<Loader2 size={16} className="animate-spin"/>:"+"} Create</button></div></div>{error&&<div className="learn-card mb-5 border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}<div className="space-y-4">{rooms.map(r=><div key={r.id} className="learn-card flex flex-col gap-4 p-6 md:flex-row md:items-center md:justify-between"><div><div className="learn-eyebrow">{r.is_active?"Active":"Hidden"}</div><h2 className="mt-2 text-xl font-bold">{r.name}</h2>{r.description&&<p className="mt-1 text-sm text-slate-400">{r.description}</p>}</div><div className="flex gap-2"><button type="button" onClick={()=>void toggle(r)} className="learn-secondary-button">{r.is_active?"Hide":"Show"}</button><button type="button" onClick={()=>void remove(r)} className="learn-secondary-button">Delete</button></div></div>)}{!rooms.length&&<div className="learn-card p-8 text-center text-sm text-slate-400">No chatrooms yet. Create your first room.</div>}</div></LearnShell>}
