import { createFileRoute, Link } from "@tanstack/react-router";
import { Loader2, Pencil, Plus, Save, Trash2, X, Layers } from "lucide-react";
import { useEffect, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type CourseStatus = "draft" | "published" | "archived";
type AccessType = "free" | "paid" | "service";
type Course = { id: string; slug: string; title: string; description: string | null; thumbnail_url: string | null; status: CourseStatus; access_type: AccessType; duration_minutes: number | null };
const emptyForm = { slug: "", title: "", description: "", thumbnail_url: "", status: "draft" as CourseStatus, access_type: "free" as AccessType, duration_minutes: "" };

export const Route = createFileRoute("/learn/manage/courses")({ component: CourseManager });

function CourseManager() {
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [isAdmin, setIsAdmin] = useState(false); const [courses, setCourses] = useState<Course[]>([]); const [formOpen, setFormOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function loadCourses() { setLoading(true); setError(""); const { data: { user }, error: userError } = await supabase.auth.getUser(); if (userError || !user) { setError(userError?.message ?? "You are not signed in."); setLoading(false); return; } const { data: profile, error: profileError } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profileError) { setError(profileError.message); setLoading(false); return; } const admin = profile?.role === "admin"; setIsAdmin(admin); if (!admin) { setError("Only admins can manage courses."); setLoading(false); return; } const { data, error: coursesError } = await supabase.from("courses").select("id, slug, title, description, thumbnail_url, status, access_type, duration_minutes").order("created_at", { ascending: false }); if (coursesError) { setError(coursesError.message); setLoading(false); return; } setCourses((data ?? []) as Course[]); setLoading(false); }
  useEffect(() => { void loadCourses(); }, []);
  function openCreate() { setEditingId(null); setForm(emptyForm); setError(""); setSuccess(""); setFormOpen(true); }
  function openEdit(course: Course) { setEditingId(course.id); setForm({ slug: course.slug, title: course.title, description: course.description ?? "", thumbnail_url: course.thumbnail_url ?? "", status: course.status, access_type: course.access_type, duration_minutes: course.duration_minutes ? String(course.duration_minutes) : "" }); setError(""); setSuccess(""); setFormOpen(true); }
  function closeForm() { if (saving) return; setFormOpen(false); setEditingId(null); setForm(emptyForm); }
  async function saveCourse(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); const duration = form.duration_minutes.trim() ? Number(form.duration_minutes) : null; if (duration !== null && (!Number.isInteger(duration) || duration <= 0)) { setError("Duration must be a positive number of minutes."); setSaving(false); return; } const payload = { slug: form.slug.trim(), title: form.title.trim(), description: form.description.trim() || null, thumbnail_url: form.thumbnail_url.trim() || null, status: form.status, access_type: form.access_type, duration_minutes: duration }; if (!payload.slug || !payload.title) { setError("Slug and title are required."); setSaving(false); return; } const result = editingId ? await supabase.from("courses").update(payload).eq("id", editingId) : await supabase.from("courses").insert(payload); if (result.error) { setError(result.error.message); setSaving(false); return; } setSuccess(editingId ? "Course updated successfully." : "Course created successfully."); setSaving(false); setFormOpen(false); setEditingId(null); setForm(emptyForm); await loadCourses(); }
  async function deleteCourse(course: Course) { if (!window.confirm(`Delete "${course.title}"? This will also delete its modules and lessons.`)) return; setError(""); setSuccess(""); const { error: deleteError } = await supabase.from("courses").delete().eq("id", course.id); if (deleteError) { setError(deleteError.message); return; } setSuccess("Course deleted successfully."); await loadCourses(); }
  return <LearnShell>
    <SectionHeader eyebrow="Admin" title="Course Manager" description="Create and manage the learning programs available in the Coach Amit Soni Learning Hub." action={isAdmin ? <button type="button" className="learn-primary-button" onClick={openCreate}><Plus size={17}/>New course</button> : undefined} />
    {error && <div className="learn-alert error mb-5">{error}</div>}{success && <div className="learn-alert success mb-5">{success}</div>}
    {isAdmin && formOpen && <form onSubmit={saveCourse} className="reference-admin-form mb-6"><div className="flex items-center justify-between"><div><div className="learn-eyebrow">{editingId ? "Edit course" : "New course"}</div><h2 className="mt-1 text-xl font-bold">{editingId ? "Update course" : "Create course"}</h2></div><button type="button" className="learn-icon-button" onClick={closeForm} aria-label="Close form"><X size={18}/></button></div><div className="reference-admin-form-grid mt-4"><div className="reference-admin-field"><label>Title</label><input value={form.title} onChange={e=>setForm(c=>({...c,title:e.target.value}))} placeholder="Build Your First AI Agent" /></div><div className="reference-admin-field"><label>Slug</label><input value={form.slug} onChange={e=>setForm(c=>({...c,slug:e.target.value.toLowerCase().replace(/\s+/g,"-")}))} placeholder="build-your-first-ai-agent" /></div><div className="reference-admin-field full"><label>Description</label><textarea value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))} placeholder="Describe what students will learn." /></div><div className="reference-admin-field"><label>Thumbnail URL</label><input type="url" value={form.thumbnail_url} onChange={e=>setForm(c=>({...c,thumbnail_url:e.target.value}))} placeholder="https://..." /></div><div className="reference-admin-field"><label>Status</label><select value={form.status} onChange={e=>setForm(c=>({...c,status:e.target.value as CourseStatus}))}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div className="reference-admin-field"><label>Access type</label><select value={form.access_type} onChange={e=>setForm(c=>({...c,access_type:e.target.value as AccessType}))}><option value="free">Free</option><option value="paid">Paid</option><option value="service">Service</option></select></div><div className="reference-admin-field"><label>Duration (minutes)</label><input type="number" min="1" value={form.duration_minutes} onChange={e=>setForm(c=>({...c,duration_minutes:e.target.value}))} placeholder="120" /></div></div><div className="reference-admin-actions"><button type="button" className="learn-secondary-button" onClick={closeForm}>Cancel</button><button type="submit" className="learn-primary-button" disabled={saving}>{saving ? <><Loader2 size={17} className="animate-spin"/>Saving...</> : <><Save size={17}/>Save course</>}</button></div></form>}
    {loading ? <div className="learn-card flex items-center gap-3 p-6 text-slate-400"><Loader2 size={18} className="animate-spin"/>Checking admin access...</div> : isAdmin && (courses.length === 0 ? <div className="learn-card p-8 text-center"><h2 className="text-lg font-bold">No courses yet</h2><p className="mt-2 text-sm text-slate-400">Create your first course to start building your learning library.</p></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.map(course=><article key={course.id} className="learn-card overflow-hidden">{course.thumbnail_url ? <img src={course.thumbnail_url} alt="" className="h-40 w-full object-cover"/> : <div className="h-40 bg-gradient-to-br from-cyan-500/20 via-violet-500/20 to-orange-500/20"/>}<div className="p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{course.title}</h2><p className="mt-1 text-xs text-slate-500">{course.slug}</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-slate-300">{course.status}</span></div><p className="mt-4 min-h-12 text-sm leading-6 text-slate-400">{course.description || "No description added yet."}</p><div className="mt-3 text-xs text-slate-500">{course.access_type} · {course.duration_minutes ? `${course.duration_minutes} min` : "Duration not set"}</div><div className="mt-5 flex gap-2"><button type="button" className="learn-secondary-button flex-1" onClick={()=>openEdit(course)}><Pencil size={15}/>Edit</button><Link to="/learn/manage/course-content/$courseId" params={{courseId: course.id}} className="learn-secondary-button flex-1"><Layers size={15}/>Content</Link><button type="button" className="learn-secondary-button" onClick={()=>void deleteCourse(course)} aria-label={`Delete ${course.title}`}><Trash2 size={15}/></button></div></div></article>)}</div>)}
  </LearnShell>;
}
