import { createFileRoute, Link } from "@tanstack/react-router";
import { Loader2, Pencil, Plus, Save, Trash2, X, Layers } from "lucide-react";
import { useEffect, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type CourseStatus = "draft" | "published" | "archived";
type Course = { id: string; slug: string; title: string; description: string | null; thumbnail_url: string | null; status: CourseStatus };
const emptyForm = { slug: "", title: "", description: "", thumbnail_url: "", status: "draft" as CourseStatus };

export const Route = createFileRoute("/learn/manage/courses")({ component: CourseManager });

function CourseManager() {
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [isAdmin, setIsAdmin] = useState(false); const [courses, setCourses] = useState<Course[]>([]); const [formOpen, setFormOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const [success, setSuccess] = useState("");

  async function loadCourses() {
    setLoading(true); setError("");
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) { setError(userError?.message ?? "You are not signed in."); setLoading(false); return; }
    const { data: profile, error: profileError } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle();
    if (profileError) { setError(profileError.message); setLoading(false); return; }
    const admin = profile?.role === "admin"; setIsAdmin(admin);
    if (!admin) { setError("Only admins can manage courses."); setLoading(false); return; }
    const { data, error: coursesError } = await supabase.from("courses").select("id, slug, title, description, thumbnail_url, status").order("created_at", { ascending: false });
    if (coursesError) { setError(coursesError.message); setLoading(false); return; }
    setCourses((data ?? []) as Course[]); setLoading(false);
  }
  useEffect(() => { void loadCourses(); }, []);
  function openCreate() { setEditingId(null); setForm(emptyForm); setError(""); setSuccess(""); setFormOpen(true); }
  function openEdit(course: Course) { setEditingId(course.id); setForm({ slug: course.slug, title: course.title, description: course.description ?? "", thumbnail_url: course.thumbnail_url ?? "", status: course.status }); setError(""); setSuccess(""); setFormOpen(true); }
  function closeForm() { if (saving) return; setFormOpen(false); setEditingId(null); setForm(emptyForm); }
  async function saveCourse(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); const payload = { slug: form.slug.trim(), title: form.title.trim(), description: form.description.trim() || null, thumbnail_url: form.thumbnail_url.trim() || null, status: form.status }; if (!payload.slug || !payload.title) { setError("Slug and title are required."); setSaving(false); return; } const result = editingId ? await supabase.from("courses").update(payload).eq("id", editingId) : await supabase.from("courses").insert(payload); if (result.error) { setError(result.error.message); setSaving(false); return; } setSuccess(editingId ? "Course updated successfully." : "Course created successfully."); setSaving(false); setFormOpen(false); setEditingId(null); setForm(emptyForm); await loadCourses(); }
  async function deleteCourse(course: Course) { if (!window.confirm(`Delete "${course.title}"? This will also delete its modules and lessons.`)) return; setError(""); setSuccess(""); const { error: deleteError } = await supabase.from("courses").delete().eq("id", course.id); if (deleteError) { setError(deleteError.message); return; } setSuccess("Course deleted successfully."); await loadCourses(); }

  return <LearnShell>
    <SectionHeader eyebrow="Admin" title="Course Manager" description="Create and manage the learning programs available in the Coach Amit Soni Learning Hub." action={isAdmin ? <button type="button" className="learn-primary-button" onClick={openCreate}><Plus size={17}/>New course</button> : undefined} />
    {error && <div className="learn-card mb-5 border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
    {success && <div className="learn-card mb-5 border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-300">{success}</div>}
    {isAdmin && formOpen && <form onSubmit={saveCourse} className="learn-card mb-6 space-y-5 p-6"><div className="flex items-center justify-between"><div><div className="learn-eyebrow">{editingId ? "Edit course" : "New course"}</div><h2 className="mt-1 text-xl font-bold">{editingId ? "Update course" : "Create course"}</h2></div><button type="button" className="learn-icon-button" onClick={closeForm} aria-label="Close form"><X size={18}/></button></div><div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="course-title" className="mb-2 block text-sm font-medium">Title</label><input id="course-title" value={form.title} onChange={e=>setForm(c=>({...c,title:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/60" placeholder="Build Your First AI Agent" /></div><div><label htmlFor="course-slug" className="mb-2 block text-sm font-medium">Slug</label><input id="course-slug" value={form.slug} onChange={e=>setForm(c=>({...c,slug:e.target.value.toLowerCase().replace(/\s+/g,"-")}))} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/60" placeholder="build-your-first-ai-agent" /></div></div><div><label htmlFor="course-description" className="mb-2 block text-sm font-medium">Description</label><textarea id="course-description" rows={4} value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))} className="w-full resize-none rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/60" placeholder="Describe what students will learn." /></div><div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="course-thumbnail" className="mb-2 block text-sm font-medium">Thumbnail URL</label><input id="course-thumbnail" type="url" value={form.thumbnail_url} onChange={e=>setForm(c=>({...c,thumbnail_url:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/60" placeholder="https://..." /></div><div><label htmlFor="course-status" className="mb-2 block text-sm font-medium">Status</label><select id="course-status" value={form.status} onChange={e=>setForm(c=>({...c,status:e.target.value as CourseStatus}))} className="w-full rounded-xl border border-white/10 bg-[#111d2d] px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/60"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div></div><div className="flex justify-end gap-3"><button type="button" className="learn-secondary-button" onClick={closeForm}>Cancel</button><button type="submit" className="learn-primary-button" disabled={saving}>{saving ? <><Loader2 size={17} className="animate-spin"/>Saving...</> : <><Save size={17}/>Save course</>}</button></div></form>}
    {loading ? <div className="learn-card flex items-center gap-3 p-6 text-slate-400"><Loader2 size={18} className="animate-spin"/>Checking admin access...</div> : isAdmin && (courses.length === 0 ? <div className="learn-card p-8 text-center"><h2 className="text-lg font-bold">No courses yet</h2><p className="mt-2 text-sm text-slate-400">Create your first course to start building your learning library.</p></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.map(course=><article key={course.id} className="learn-card overflow-hidden">{course.thumbnail_url ? <img src={course.thumbnail_url} alt="" className="h-40 w-full object-cover"/> : <div className="h-40 bg-gradient-to-br from-cyan-500/20 via-violet-500/20 to-orange-500/20"/>}<div className="p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{course.title}</h2><p className="mt-1 text-xs text-slate-500">{course.slug}</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-slate-300">{course.status}</span></div><p className="mt-4 min-h-12 text-sm leading-6 text-slate-400">{course.description || "No description added yet."}</p><div className="mt-5 flex gap-2"><button type="button" className="learn-secondary-button flex-1" onClick={()=>openEdit(course)}><Pencil size={15}/>Edit</button><Link to="/learn/manage/courses/$courseId" params={{courseId: course.id}} className="learn-secondary-button flex-1"><Layers size={15}/>Content</Link><button type="button" className="learn-secondary-button" onClick={()=>void deleteCourse(course)} aria-label={`Delete ${course.title}`}><Trash2 size={15}/></button></div></div></article>)}</div>)}
  </LearnShell>;
}
