import { createFileRoute } from "@tanstack/react-router";
import { Download, Loader2, Mail, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";
import { sendLearningEmail } from "@/lib/learningEmail";

type Row={student:string;programs:string;progress:number;completedCourses:number;workshops:number;certificates:number};
export const Route=createFileRoute("/learn/manage/reports")({component:Reports});
function Reports(){const[rows,setRows]=useState<Row[]>([]),[program,setProgram]=useState("all"),[query,setQuery]=useState(""),[programs,setPrograms]=useState<{id:string;title:string}[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[emailStatus,setEmailStatus]=useState("");
useEffect(()=>{async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in.");setLoading(false);return}const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me?.role!=="admin"){setError("Only admins can view reports.");setLoading(false);return}const[st,pr,en,co,mo,le,lp,ce,wr]=await Promise.all([supabase.from("profiles").select("id,full_name").eq("role","student"),supabase.from("programs").select("id,title").order("sort_order"),supabase.from("program_enrollments").select("user_id,program_id,status"),supabase.from("courses").select("id,title,program_id"),supabase.from("course_modules").select("id,course_id"),supabase.from("course_lessons").select("id,module_id"),supabase.from("lesson_progress").select("user_id,lesson_id,completed"),supabase.from("course_certificates").select("user_id,course_id"),supabase.from("workshop_registrations").select("user_id")]);const err=st.error||pr.error||en.error||co.error||mo.error||le.error||lp.error||ce.error||wr.error;if(err){setError(err.message);setLoading(false);return}const P=pr.data||[],C=co.data||[],M=mo.data||[],L=le.data||[],LP=lp.data||[];setPrograms(P as any);const result=(st.data||[]).map((s:any)=>{const es=(en.data||[]).filter((e:any)=>e.user_id===s.id&&e.status!=="cancelled"),pids=new Set(es.map((e:any)=>e.program_id)),cs=C.filter((c:any)=>pids.has(c.program_id)),mids=new Set(M.filter((m:any)=>cs.some((c:any)=>c.id===m.course_id)).map((m:any)=>m.id)),ls=L.filter((l:any)=>mids.has(l.module_id)),done=new Set(LP.filter((p:any)=>p.user_id===s.id&&p.completed).map((p:any)=>p.lesson_id));const completedCourses=cs.filter((c:any)=>{const cmids=new Set(M.filter((m:any)=>m.course_id===c.id).map((m:any)=>m.id)),cl=L.filter((l:any)=>cmids.has(l.module_id));return cl.length>0&&cl.every((l:any)=>done.has(l.id))}).length;return{student:s.full_name||"Student",programs:es.map((e:any)=>P.find((p:any)=>p.id===e.program_id)?.title||"Program").join("; "),progress:ls.length?Math.round(ls.filter((l:any)=>done.has(l.id)).length/ls.length*100):0,completedCourses,workshops:(wr.data||[]).filter((x:any)=>x.user_id===s.id).length,certificates:(ce.data||[]).filter((x:any)=>x.user_id===s.id).length}});setRows(result);setLoading(false)}void load()},[]);
const filtered=useMemo(()=>rows.filter(r=>(program==="all"||r.programs.split("; ").includes(programs.find(p=>p.id===program)?.title||""))&&r.student.toLowerCase().includes(query.toLowerCase())),[rows,program,programs,query]);
function csv(){const esc=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;const text=["Student,Programs,Overall Progress %,Completed Courses,Workshop Registrations,Certificates",...filtered.map(r=>[r.student,r.programs,r.progress,r.completedCourses,r.workshops,r.certificates].map(esc).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=`coachamitsoni-student-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function testEmail(){setEmailStatus("Sending test email...");try{const{data:{user}}=await supabase.auth.getUser();if(!user?.email)throw new Error("The signed-in Admin account has no email address.");const result=await sendLearningEmail(user.email,"CoachAmitSoni LMS — Email test",`<div style="font-family:Arial,sans-serif"><h2>Email configuration test</h2><p>This is a test email from the CoachAmitSoni Learning Hub.</p><p>Your Resend connection and LMS email sender are configured successfully.</p></div>`);if(result?.configured===false)throw new Error(result.message||"Email provider is not configured.");setEmailStatus("Test email sent. Check the Admin inbox.")}catch(e){setEmailStatus(e instanceof Error?e.message:"Unable to send test email.")}}
if(loading)return <LearnShell><div className="learn-card p-6 text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={18}/>Loading reports...</div></LearnShell>;return <LearnShell><SectionHeader eyebrow="Admin · Reports" title="Reports" description="Read-only overview of student enrolment, learning progress, workshops and certificates." action={<div className="flex flex-wrap gap-2"><button onClick={testEmail} className="learn-secondary-button"><Mail size={16}/>Send test email</button><button onClick={csv} disabled={!filtered.length} className="learn-primary-button"><Download size={16}/>Export CSV</button></div>}/>{emailStatus&&<div className="mb-4 learn-card p-4 text-sm text-slate-300">{emailStatus}</div>}{error?<div className="learn-card p-6 text-red-300">{error}</div>:<><div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Students" value={rows.length}/><Stat label="Average progress" value={`${rows.length?Math.round(rows.reduce((a,r)=>a+r.progress,0)/rows.length):0}%`}/><Stat label="Completed courses" value={rows.reduce((a,r)=>a+r.completedCourses,0)}/><Stat label="Certificates" value={rows.reduce((a,r)=>a+r.certificates,0)}/></div><div className="learn-card p-4"><div className="grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search className="absolute left-3 top-3 text-slate-500" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students" className="w-full rounded-xl border border-white/10 bg-white/5 py-2.5 pl-9 text-sm text-white"/></div><select value={program} onChange={e=>setProgram(e.target.value)} className="rounded-xl border border-white/10 bg-[#172333] px-3 text-sm text-white"><option value="all">All programs</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-white/8 text-xs uppercase tracking-wider text-slate-500"><th className="px-3 py-3">Student</th><th className="px-3 py-3">Programs</th><th className="px-3 py-3">Progress</th><th className="px-3 py-3">Courses</th><th className="px-3 py-3">Workshops</th><th className="px-3 py-3">Certificates</th></tr></thead><tbody>{filtered.map(r=><tr key={r.student} className="border-b border-white/5"><td className="px-3 py-4 font-semibold">{r.student}</td><td className="max-w-[260px] px-3 py-4 text-slate-400">{r.programs||"—"}</td><td className="px-3 py-4 font-semibold text-cyan-300">{r.progress}%</td><td className="px-3 py-4">{r.completedCourses}</td><td className="px-3 py-4">{r.workshops}</td><td className="px-3 py-4">{r.certificates}</td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="px-3 py-8 text-center text-slate-500">No students match the current filters.</td></tr>}</tbody></table></div></div></>}</LearnShell>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="learn-card p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>}
