import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, CalendarDays, Check, Loader2, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type Workshop={id:string;title:string;starts_at:string|null;ends_at:string|null;status:string};
type Registration={id:string;user_id:string;workshop_id:string;status:string;registered_at:string};
type Profile={id:string;full_name:string|null;role:string};
export const Route=createFileRoute("/learn/manage/workshop-registrations")({component:Registrations});
function Registrations(){const[ws,setWs]=useState<Workshop[]>([]);const[regs,setRegs]=useState<Registration[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[selected,setSelected]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[saving,setSaving]=useState("");
async function load(){setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("You are not signed in.");setLoading(false);return}const{data:p}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(p?.role!=="admin"){setError("Only admins can view workshop registrations.");setLoading(false);return}const[{data:w,error:we},{data:r,error:re}]=await Promise.all([supabase.from("workshops").select("id,title,starts_at,ends_at,status").order("starts_at",{ascending:false,nullsFirst:false}),supabase.from("workshop_registrations").select("id,user_id,workshop_id,status,registered_at").order("registered_at",{ascending:false})]);if(we||re){setError((we||re)?.message||"Unable to load registrations.");setLoading(false);return}const rs=(r||[])as Registration[];const ids=[...new Set(rs.map(x=>x.user_id))];let ps:Profile[]=[];if(ids.length){const{data:pd,error:pe}=await supabase.from("profiles").select("id,full_name,role").in("id",ids);if(pe){setError(pe.message);setLoading(false);return}ps=(pd||[])as Profile[]}setWs((w||[])as Workshop[]);setRegs(rs);setProfiles(ps);if(!selected&&w?.length)setSelected(w[0].id);setLoading(false)}
useEffect(()=>{void load()},[]);
const current=useMemo(()=>ws.find(w=>w.id===selected)||null,[ws,selected]);const rows=useMemo(()=>regs.filter(r=>r.workshop_id===selected),[regs,selected]);const name=(id:string)=>profiles.find(p=>p.id===id)?.full_name||"Student";
async function mark(id:string,status:string){setSaving(id);setError("");const{error:e}=await supabase.from("workshop_registrations").update({status}).eq("id",id);if(e)setError(e.message);else setRegs(rs=>rs.map(r=>r.id===id?{...r,status}:r));setSaving("")}
if(loading)return <LearnShell><div className="learn-card p-6 text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={18}/>Loading registrations...</div></LearnShell>;
return <LearnShell><div className="mb-5"><Link to="/learn/manage/workshops" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={15}/>Back to Workshops</Link></div><SectionHeader eyebrow="Admin · Live learning" title="Workshop registrations" description="See who registered and record attendance."/>{error&&<div className="learn-card mb-5 border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{!ws.length?<div className="learn-card p-8 text-center text-sm text-slate-400">No workshops yet.</div>:<><div className="learn-card mb-6 p-4"><label className="text-sm text-slate-300">Workshop<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white">{ws.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label></div><div className="learn-card p-6"><div className="flex flex-col gap-3 border-b border-white/10 pb-5 md:flex-row md:items-center md:justify-between"><div><div className="learn-eyebrow">{current?.status}</div><h2 className="mt-2 text-xl font-bold">{current?.title}</h2></div><div className="flex flex-wrap gap-2 text-xs text-slate-400">{current?.starts_at&&<span className="learn-meta"><CalendarDays size={14}/>{new Date(current.starts_at).toLocaleString()}</span>}<span className="learn-meta"><Users size={14}/>{rows.filter(r=>r.status!=="cancelled").length} registered</span></div></div>{!rows.length?<p className="py-8 text-center text-sm text-slate-400">No registrations yet.</p>:<div className="mt-5 space-y-3">{rows.map(r=><div key={r.id} className="flex flex-col gap-3 rounded-xl border border-white/8 bg-white/[.03] p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-medium text-slate-200">{name(r.user_id)}</div><div className="mt-1 text-xs text-slate-500">Registered {new Date(r.registered_at).toLocaleString()}</div></div><div className="flex items-center gap-2"><span className="learn-secondary-button">{r.status}</span>{r.status!=="attended"&&r.status!=="cancelled"&&<button type="button" disabled={saving===r.id} onClick={()=>void mark(r.id,"attended")} className="learn-primary-button">{saving===r.id?<Loader2 size={14} className="animate-spin"/>:<Check size={14}/>} Mark attended</button>}{r.status!=="cancelled"&&r.status!=="attended"&&<button type="button" disabled={saving===r.id} onClick={()=>void mark(r.id,"cancelled")} className="learn-secondary-button">Cancel</button>}</div></div>)}</div>}</div></>}</LearnShell>}
