import { createFileRoute } from "@tanstack/react-router";
import { Bell, Check, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type Notification={id:string;title:string;body:string|null;read_at:string|null;created_at:string};
export const Route=createFileRoute("/learn/notifications")({component:Notifications});
function Notifications(){const[items,setItems]=useState<Notification[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");
async function load(){setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in to continue.");setLoading(false);return}const{data,error:e}=await supabase.from("notifications").select("id,title,body,read_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false});if(e)setError(e.message);else setItems((data||[])as Notification[]);setLoading(false)}
useEffect(()=>{void load()},[]);
async function markRead(id:string){setBusy(id);const{error:e}=await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else setItems(xs=>xs.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x));setBusy("")}
async function markAll(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;setBusy("all");const now=new Date().toISOString();const{error:e}=await supabase.from("notifications").update({read_at:now}).eq("user_id",user.id).is("read_at",null);if(e)setError(e.message);else setItems(xs=>xs.map(x=>({...x,read_at:x.read_at||now})));setBusy("")}
const unread=items.filter(x=>!x.read_at).length;
return <LearnShell><SectionHeader eyebrow="Updates" title="Notifications" description="Workshop reminders, course updates and learning announcements." action={unread>0?<button type="button" onClick={()=>void markAll()} disabled={busy==="all"} className="learn-secondary-button">{busy==="all"?<Loader2 size={15} className="animate-spin"/>:<Check size={15}/>}Mark all read</button>:undefined}/>{error&&<div className="learn-card mb-5 border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{loading?<div className="learn-card flex items-center gap-3 p-6 text-sm text-slate-400"><Loader2 size={18} className="animate-spin"/>Loading notifications...</div>:!items.length?<div className="learn-card p-8 text-center"><div className="learn-icon-tile mx-auto"><Bell size={20}/></div><h2 className="mt-4 text-lg font-bold">No new notifications</h2><p className="mt-2 text-sm text-slate-400">You’re all caught up.</p></div>:<div className="space-y-3">{items.map(n=><article key={n.id} className={`learn-card p-5 ${!n.read_at?"border-cyan-400/30":""}`}><div className="flex gap-4"><div className="learn-icon-tile shrink-0"><Bell size={18}/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{n.title}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{n.body}</p></div>{!n.read_at&&<span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-cyan-300"/>}</div><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{new Date(n.created_at).toLocaleString()}</span>{!n.read_at&&<button type="button" onClick={()=>void markRead(n.id)} disabled={busy===n.id} className="learn-secondary-button">{busy===n.id?<Loader2 size={14} className="animate-spin"/>:<Check size={14}/>}Mark read</button>}</div></div></div></article>)}</div>}</LearnShell>}
