import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, Check, Clock3, ExternalLink, Loader2, Video } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type Workshop={id:string;title:string;description:string|null;starts_at:string|null;ends_at:string|null;format:string|null;status:string;meeting_url:string|null};
export const Route=createFileRoute("/learn/workshops")({component:Workshops});
function isCompleted(w:Workshop){if(w.status==="completed")return true;if(w.status==="cancelled")return false;const end=w.ends_at||w.starts_at;return !!end&&new Date(end).getTime()<=Date.now()}
function Workshops(){const[items,setItems]=useState<Workshop[]>([]);const[registered,setRegistered]=useState<Set<string>>(new Set());const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[success,setSuccess]=useState("");const[tab,setTab]=useState<"upcoming"|"completed">("upcoming");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in to continue.");setLoading(false);return}const[{data:ws,error:we},{data:regs,error:re}]=await Promise.all([supabase.from("workshops").select("id,title,description,starts_at,ends_at,format,status,meeting_url").in("status",["upcoming","completed"]).order("starts_at",{ascending:true,nullsFirst:false}),supabase.from("workshop_registrations").select("workshop_id,status").eq("user_id",user.id)]);if(we||re)setError((we||re)?.message||"Unable to load workshops.");else{setItems((ws||[])as Workshop[]);setRegistered(new Set((regs||[]).filter(r=>r.status!=="cancelled").map(r=>r.workshop_id)))}setLoading(false)}
useEffect(()=>{void load()},[]);const upcoming=useMemo(()=>items.filter(w=>w.status!=="cancelled"&&!isCompleted(w)),[items]);const completed=useMemo(()=>items.filter(w=>isCompleted(w)),[items]);const visible=tab==="upcoming"?upcoming:completed;
async function register(id:string){setBusy(id);setError("");setSuccess("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in to register.");setBusy("");return}const workshop=items.find(w=>w.id===id);if(!workshop||isCompleted(workshop)){setError("This workshop has already completed.");setBusy("");return}const{data:existing,error:lookupError}=await supabase.from("workshop_registrations").select("id,status").eq("user_id",user.id).eq("workshop_id",id).maybeSingle();if(lookupError){setError(lookupError.message);setBusy("");return}const{error:e}=await supabase.from("workshop_registrations").upsert({user_id:user.id,workshop_id:id,status:"registered"},{onConflict:"user_id,workshop_id"});if(e)setError(e.message);else{setRegistered(s=>new Set(s).add(id));if(workshop&&(!existing||existing.status==="cancelled")){const when=workshop.starts_at?` on ${new Date(workshop.starts_at).toLocaleString()}`:"";const{error:ne}=await supabase.from("notifications").insert({user_id:user.id,title:"Workshop registration confirmed",body:`You’re registered for ${workshop.title}${when}.`});if(ne){console.error("Workshop notification failed",ne);}const { error:emailError } = await supabase.functions.invoke("send-workshop-registration-email", { body: { workshop_id: id } });if(emailError)setSuccess("Registration successful. Your workshop access is updated; the confirmation email could not be sent.");else setSuccess("Registration successful. Confirmation email sent to your registered email.");}else setSuccess("Registration successful.");}setBusy("")}
if(loading)return <LearnShell><div className="learn-card p-6 text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={18}/>Loading workshops...</div></LearnShell>;
return <LearnShell><SectionHeader eyebrow="Live learning" title="Workshops" description="Join live learning sessions and practical workshops."/><div className="learn-tab-list mb-6" role="tablist" aria-label="Workshop status"><button type="button" role="tab" aria-selected={tab==="upcoming"} onClick={()=>setTab("upcoming")} className={`learn-tab ${tab==="upcoming"?"active":""}`}>Upcoming <span className="ml-1 text-xs text-slate-500">{upcoming.length}</span></button><button type="button" role="tab" aria-selected={tab==="completed"} onClick={()=>setTab("completed")} className={`learn-tab ${tab==="completed"?"active":""}`}>Completed <span className="ml-1 text-xs text-slate-500">{completed.length}</span></button></div>{error&&<div className="learn-card mb-5 border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300" role="alert">{error}</div>}{success&&<div className="learn-card mb-5 border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm font-medium text-emerald-300" role="status"><Check className="mr-2 inline" size={18}/>{success}</div>}{!visible.length?<div className="learn-card p-8 text-center text-sm text-slate-400">{tab==="upcoming"?"No upcoming workshops right now.":"No completed workshops yet."}</div>:<div className="space-y-4">{visible.map(w=><article key={w.id} className="learn-card overflow-hidden p-0"><div className="h-1 bg-gradient-to-r from-cyan-400 via-violet-500 to-orange-400"/><div className="p-6 md:flex md:items-center md:justify-between md:gap-8"><div className="min-w-0"><div className="learn-eyebrow">{tab==="upcoming"?"Upcoming workshop":"Completed workshop"}</div><h2 className="mt-2 text-2xl font-bold">{w.title}</h2>{w.description&&<p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{w.description}</p>}<div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-400">{w.starts_at&&<span className="learn-meta"><CalendarDays size={14}/>{new Date(w.starts_at).toLocaleString()}</span>}{w.ends_at&&<span className="learn-meta"><Clock3 size={14}/>{new Date(w.ends_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</span>}{w.format&&<span className="learn-meta"><Video size={14}/>{w.format}</span>}{tab==="completed"&&registered.has(w.id)&&<span className="learn-status-pill learn-status-registered"><Check size={13}/>Registered</span>}</div></div><div className="mt-5 flex flex-wrap items-center gap-2 md:mt-0">{tab==="upcoming"&&!registered.has(w.id)&&<button type="button" onClick={()=>void register(w.id)} disabled={busy===w.id} className="learn-primary-button">{busy===w.id?<Loader2 size={15} className="animate-spin"/>:"Register"}</button>}{tab==="upcoming"&&registered.has(w.id)&&<span className="learn-status-pill learn-status-registered"><Check size={13}/>Registered</span>}{tab==="upcoming"&&registered.has(w.id)&&w.meeting_url&&<a href={w.meeting_url} target="_blank" rel="noreferrer" className="learn-primary-button">Join workshop <ExternalLink size={15}/></a>}</div></div></article>)}</div>}</LearnShell>}
