import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, Clock3, ExternalLink, Loader2, Video } from "lucide-react";
import { useEffect, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

type Workshop={id:string;title:string;description:string|null;starts_at:string|null;ends_at:string|null;format:string|null;status:string;meeting_url:string|null};
export const Route=createFileRoute("/learn/workshops")({component:Workshops});
function Workshops(){const[items,setItems]=useState<Workshop[]>([]);const[registered,setRegistered]=useState<Set<string>>(new Set());const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in to continue.");setLoading(false);return}const[{data:ws,error:we},{data:regs,error:re}]=await Promise.all([supabase.from("workshops").select("id,title,description,starts_at,ends_at,format,status,meeting_url").in("status",["upcoming","completed"]).order("starts_at",{ascending:true,nullsFirst:false}),supabase.from("workshop_registrations").select("workshop_id,status").eq("user_id",user.id)]);if(we||re)setError((we||re)?.message||"Unable to load workshops.");else{setItems((ws||[])as Workshop[]);setRegistered(new Set((regs||[]).filter(r=>r.status!=="cancelled").map(r=>r.workshop_id)))}setLoading(false)}
useEffect(()=>{void load()},[]);
async function register(id:string){setBusy(id);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in to register.");setBusy("");return}const workshop=items.find(w=>w.id===id);const{error:e}=await supabase.from("workshop_registrations").upsert({user_id:user.id,workshop_id:id,status:"registered"},{onConflict:"user_id,workshop_id"});if(e)setError(e.message);else{setRegistered(s=>new Set(s).add(id));if(workshop){const when=workshop.starts_at?` on ${new Date(workshop.starts_at).toLocaleString()}`:"";const{error:ne}=await supabase.from("notifications").insert({user_id:user.id,title:"Workshop registration confirmed",body:`You’re registered for ${workshop.title}${when}.`});if(ne)setError(ne.message)}}setBusy("")}
if(loading)return <LearnShell><div className="learn-card p-6 text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={18}/>Loading workshops...</div></LearnShell>;
return <LearnShell><SectionHeader eyebrow="Live learning" title="Workshops" description="Join live learning sessions and practical workshops."/>{error&&<div className="learn-card mb-5 border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{!items.length?<div className="learn-card p-8 text-center text-sm text-slate-400">No workshops available right now.</div>:<div className="space-y-4">{items.map(w=><article key={w.id} className="learn-card overflow-hidden p-0"><div className="h-1 bg-gradient-to-r from-cyan-400 via-violet-500 to-orange-400"/><div className="p-6 md:flex md:items-center md:justify-between md:gap-8"><div><div className="learn-eyebrow">{w.status==='upcoming'?"Upcoming workshop":"Workshop"}</div><h2 className="mt-2 text-2xl font-bold">{w.title}</h2>{w.description&&<p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{w.description}</p>}<div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-400">{w.starts_at&&<span className="learn-meta"><CalendarDays size={14}/>{new Date(w.starts_at).toLocaleString()}</span>}{w.ends_at&&<span className="learn-meta"><Clock3 size={14}/>{new Date(w.ends_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</span>}{w.format&&<span className="learn-meta"><Video size={14}/>{w.format}</span>}</div></div><div className="mt-5 flex flex-wrap gap-2 md:mt-0">{w.status==='upcoming'&&!registered.has(w.id)&&<button type="button" onClick={()=>void register(w.id)} disabled={busy===w.id} className="learn-primary-button">{busy===w.id?<Loader2 size={15} className="animate-spin"/>:"Register"}</button>}{registered.has(w.id)&&<span className="learn-secondary-button">Registered</span>}{registered.has(w.id)&&w.meeting_url&&<a href={w.meeting_url} target="_blank" rel="noreferrer" className="learn-primary-button">Join workshop <ExternalLink size={15}/></a>}</div></div></article>)}</div>}</LearnShell>}
