import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ChevronRight, FileText, Film, Link2, Loader2, LockKeyhole, Star } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { LearnShell } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/learn/courses/$slug")({component:CourseDetail});
type Course={id:string;slug:string;title:string;description:string|null;thumbnail_url:string|null;status:string};
type Module={id:string;title:string;description:string|null;sort_order:number};
type Lesson={id:string;module_id:string;title:string;description:string|null;content_url:string|null;content_body:string|null;content_storage_path:string|null;content_type:string|null;sort_order:number;is_preview:boolean};
function youtube(url:string|null){if(!url)return null;try{const u=new URL(url);if(u.hostname.includes("youtube.com")){const id=u.searchParams.get("v");return id?`https://www.youtube.com/embed/${id}`:null}if(u.hostname==="youtu.be")return `https://www.youtube.com/embed/${u.pathname.slice(1)}`}catch{}return null}
function CourseDetail(){const {slug}=Route.useParams();const [course,setCourse]=useState<Course|null>(null);const [modules,setModules]=useState<Module[]>([]);const [lessons,setLessons]=useState<Lesson[]>([]);const [completed,setCompleted]=useState<Set<string>>(new Set());const [selected,setSelected]=useState<string|null>(null);const [url,setUrl]=useState<string|null>(null);const [enrolled,setEnrolled]=useState(false);const [isAdmin,setIsAdmin]=useState(false);const [loading,setLoading]=useState(true);const [loadingLesson,setLoadingLesson]=useState(false);const [error,setError]=useState("");const [expanded,setExpanded]=useState<Set<string>>(new Set());const [rating,setRating]=useState(0);
 const selectedLesson=lessons.find(l=>l.id===selected)||null;const index=selectedLesson?lessons.findIndex(l=>l.id===selectedLesson.id):-1;const prev=index>0?lessons[index-1]:null;const next=index>=0&&index<lessons.length-1?lessons[index+1]:null;const doneCount=lessons.filter(l=>completed.has(l.id)).length;const progress=lessons.length?Math.round(doneCount/lessons.length*100):0;const complete=progress===100&&lessons.length>0;
 const moduleStats=useMemo(()=>new Map(modules.map(m=>[m.id,lessons.filter(l=>l.module_id===m.id).length])),[modules,lessons]);
 async function load(){setLoading(true);setError("");const {data:c,error:ce}=await supabase.from("courses").select("id,slug,title,description,thumbnail_url,status").eq("slug",slug).eq("status","published").maybeSingle();if(ce||!c){setError(ce?.message||"Course not found.");setLoading(false);return}setCourse(c as Course);const {data:ms,error:me}=await supabase.from("course_modules").select("id,title,description,sort_order").eq("course_id",c.id).order("sort_order");if(me){setError(me.message);setLoading(false);return}const mm=(ms||[]) as Module[];setModules(mm);setExpanded(new Set(mm.map(m=>m.id)));const ids=mm.map(m=>m.id);const {data:ls,error:le}=await supabase.from("course_lessons").select("id,module_id,title,description,content_url,content_body,content_storage_path,content_type,sort_order,is_preview").in("module_id",ids.length?ids:["00000000-0000-0000-0000-000000000000"]).order("sort_order");if(le){setError(le.message);setLoading(false);return}const ll=(ls||[]) as Lesson[];setLessons(ll);const {data:{user}}=await supabase.auth.getUser();if(user){const {data:p}=await supabase.from("lesson_progress").select("lesson_id,completed").eq("user_id",user.id).in("lesson_id",ll.map(l=>l.id));setCompleted(new Set((p||[]).filter((x:{completed:boolean})=>x.completed).map((x:{lesson_id:string})=>x.lesson_id)));const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();const admin=profile?.role==='admin';setIsAdmin(admin);if(admin)setEnrolled(true);else{const {data:e}=await supabase.from("enrollments").select("id").eq("user_id",user.id).eq("course_id",c.id).in("status",["active","completed"]).maybeSingle();setEnrolled(Boolean(e))}const saved=window.localStorage.getItem(`course-rating:${c.id}`);if(saved)setRating(Number(saved))}setLoading(false)}
 useEffect(()=>{void load()},[slug]);
 async function openLesson(lesson:Lesson){const {data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in to access this course.");return}const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();const admin=profile?.role==='admin';if(!admin){const {data:e}=await supabase.from("enrollments").select("id").eq("user_id",user.id).eq("course_id",course?.id||"").in("status",["active","completed"]).maybeSingle();if(!e){setEnrolled(false);setSelected(null);setUrl(null);setError("Course enrolment is required to open lessons.");return}}const {data:fresh}=await supabase.from("course_lessons").select("id,module_id,title,description,content_url,content_body,content_storage_path,content_type,sort_order,is_preview").eq("id",lesson.id).maybeSingle();if(!fresh){setError("This lesson is no longer available.");return}setSelected(fresh.id);setLoadingLesson(true);setError("");let resource=fresh.content_url;if(fresh.content_storage_path){const {data,error:e}=await supabase.storage.from("course-content").createSignedUrl(fresh.content_storage_path,60);if(e){setError(e.message)}else resource=data?.signedUrl||null}setUrl(resource);setLoadingLesson(false);if(!completed.has(fresh.id)&&!admin){const {error:e}=await supabase.from("lesson_progress").upsert({user_id:user.id,lesson_id:fresh.id,completed:true,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id,lesson_id"});if(!e)setCompleted(s=>new Set(s).add(fresh.id))}window.scrollTo({top:0,behavior:"smooth"})}
 function rate(value:number){setRating(value);if(course)window.localStorage.setItem(`course-rating:${course.id}`,String(value))}
 if(loading)return <LearnShell><div className="learn-card p-8 flex items-center gap-3"><Loader2 size={18} className="animate-spin"/>Loading course...</div></LearnShell>;
 if(!course)return <LearnShell><div className="learn-card p-6"><Link to="/learn/courses" className="learn-secondary-button"><ArrowLeft size={15}/>Back to courses</Link><p className="mt-5 text-red-600">{error||"Course not found."}</p></div></LearnShell>;
 return <LearnShell><Link to="/learn/courses" className="reference-back"><ArrowLeft size={15}/>Back to courses</Link>
  <section className="reference-course-hero mt-5"><div className="grid gap-7 md:grid-cols-[290px_1fr] md:items-start">{course.thumbnail_url?<img src={course.thumbnail_url} alt="" className="w-full rounded-lg object-cover"/>:<div className="flex h-40 items-center justify-center rounded-lg bg-slate-100"><FileText size={42}/></div>}<div><h1 className="text-2xl font-bold md:text-3xl">{course.title}</h1><p className="mt-2 text-sm leading-6">{course.description||"Complete the lessons in this course at your own pace."}</p>{complete?<div className="reference-complete mt-5 p-4"><div className="flex items-center gap-3"><CheckCircle2 size={20}/><strong>Congrats! You've completed the course.</strong></div><div className="reference-rate mt-4"><span className="text-sm">Rate this course</span>{[1,2,3,4,5].map(v=><button key={v} type="button" className={`reference-star ${rating>=v?'selected':''}`} onClick={()=>rate(v)} aria-label={`Rate ${v} out of 5`}><Star size={22} fill={rating>=v?'currentColor':'none'}/></button>)}</div></div>:<div className="mt-5 flex items-center gap-4"><div className="h-2 flex-1 max-w-sm overflow-hidden rounded-full bg-slate-200"><div className="learn-progress-fill h-full rounded-full" style={{width:`${progress}%`}}/></div><span className="text-sm font-semibold">{progress}%</span></div>}<button type="button" onClick={()=>{const target=complete?lessons[0]:selectedLesson||lessons[0];if(target)void openLesson(target)}} className="learn-course-action mt-4 w-auto px-6">{complete?'View again':'Start learning'}<ArrowRight size={16}/></button></div></div></section>
  {!enrolled&&!isAdmin&&<div className="reference-lock mt-4"><LockKeyhole size={17}/><span><strong>Course access required.</strong> An administrator must enrol you before lessons can be opened.</span></div>}
  {error&&<div className="mt-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <section className="reference-course-outline mt-5"><div className="border-b border-slate-200 px-5 py-5"><h2 className="text-xl font-bold">Contents</h2><p className="mt-1 text-sm">{modules.length} sections • {lessons.length} lectures</p></div>{modules.map((m,mi)=>{const open=expanded.has(m.id);const ml=lessons.filter(l=>l.module_id===m.id);return <div key={m.id} className="border-b border-slate-200 last:border-0"><button type="button" onClick={()=>setExpanded(s=>{const n=new Set(s);n.has(m.id)?n.delete(m.id):n.add(m.id);return n})} className="flex w-full items-center gap-3 px-5 py-4 text-left"><span>{open?<ChevronDown size={17}/>:<ChevronRight size={17}/>}</span><span className="flex-1 font-semibold">{m.title}</span><span className="text-xs text-slate-500">{moduleStats.get(m.id)||0} lectures</span></button>{open&&ml.map((l,li)=><button key={l.id} type="button" disabled={!enrolled&&!isAdmin} onClick={()=>void openLesson(l)} className={`reference-outline-item w-full text-left ${completed.has(l.id)?'done':''} ${selected===l.id?'bg-amber-50':''}`}><span className="w-6 text-center text-xs font-bold">{String(li+1).padStart(2,'0')}</span>{completed.has(l.id)?<CheckCircle2 size={16}/>:l.content_type==='video'?<Film size={16}/>:l.content_type==='pdf'?<FileText size={16}/>:<Link2 size={16}/>}<span className="flex-1">{l.title}</span><span className="text-xs text-slate-400">{l.content_type||'content'}</span></button>)}</div>})}</section>
  {selectedLesson&&<section className="reference-player mt-5"><div className="reference-player-frame">{loadingLesson?<Loader2 className="animate-spin"/>:youtube(url)?<iframe src={youtube(url)||undefined} title={selectedLesson.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:selectedLesson.content_type==='video'&&url?<video src={url} controls className="h-full w-full"/>:selectedLesson.content_type==='pdf'&&url?<iframe src={url} title={selectedLesson.title}/>:selectedLesson.content_body?<div className="h-full overflow-auto bg-white p-6 text-left text-sm leading-7" dangerouslySetInnerHTML={{__html:selectedLesson.content_body}}/>:url?<a href={url} target="_blank" rel="noreferrer" className="learn-course-action w-auto px-6">Open content</a>:<div className="text-slate-500">No content available.</div>}</div><div className="border-t border-slate-200 p-5"><h2 className="text-xl font-bold">{selectedLesson.title}</h2><p className="mt-2 text-sm leading-6">{selectedLesson.description}</p><div className="mt-5 flex justify-between gap-3"><button type="button" disabled={!prev} onClick={()=>void openLesson(prev)} className="learn-secondary-button disabled:opacity-40"><ArrowLeft size={15}/>Previous</button><button type="button" disabled={!next} onClick={()=>void openLesson(next)} className="learn-primary-button disabled:opacity-40">Next<ArrowRight size={15}/></button></div></div></section>}
 </LearnShell>}
