import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Search, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { LearnShell, SectionHeader } from "@/components/learn/LearnShell";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/learn/courses")({ component: Courses });
type Course={id:string;slug:string;title:string;description:string|null;thumbnail_url:string|null;status:string};
type Enrollment={course_id:string;status:string};
type CourseCard=Course&{totalLessons:number;completedLessons:number;progress:number;enrollmentStatus:string|null};
type Filter="all"|"in-progress"|"completed"|"not-started";

function Courses(){
 const [courses,setCourses]=useState<CourseCard[]>([]); const [loading,setLoading]=useState(true); const [dbError,setDbError]=useState(""); const [query,setQuery]=useState(""); const [filter,setFilter]=useState<Filter>("all");
 useEffect(()=>{let mounted=true; async function load(){setLoading(true);setDbError(""); const {data:{user}}=await supabase.auth.getUser(); if(!user){if(mounted){setDbError("Your session could not be loaded.");setLoading(false)};return}
  const {data:published,error}=await supabase.from("courses").select("id, slug, title, description, thumbnail_url, status").eq("status","published").order("created_at",{ascending:false}); if(error){if(mounted){setDbError(error.message);setLoading(false)};return}
  const base=(published??[]) as Course[]; if(!base.length){if(mounted){setCourses([]);setLoading(false)};return} const ids=base.map(c=>c.id);
  const [{data:ens},{data:mods}]=await Promise.all([supabase.from("enrollments").select("course_id,status").eq("user_id",user.id).in("course_id",ids),supabase.from("course_modules").select("id,course_id").in("course_id",ids)]);
  const moduleRows=(mods??[]) as Array<{id:string;course_id:string}>; const moduleIds=moduleRows.map(m=>m.id); let lessons:Array<{id:string;module_id:string}>=[]; if(moduleIds.length){const {data}=await supabase.from("course_lessons").select("id,module_id").in("module_id",moduleIds);lessons=(data??[]) as Array<{id:string;module_id:string}>}
  const lessonIds=lessons.map(l=>l.id); let progress:Array<{lesson_id:string;completed:boolean}>=[]; if(lessonIds.length){const {data}=await supabase.from("lesson_progress").select("lesson_id,completed").eq("user_id",user.id).in("lesson_id",lessonIds);progress=(data??[]) as Array<{lesson_id:string;completed:boolean}>}
  const done=new Set(progress.filter(p=>p.completed).map(p=>p.lesson_id)); const em=new Map(((ens??[]) as Enrollment[]).map(e=>[e.course_id,e.status])); const mc=new Map(moduleRows.map(m=>[m.id,m.course_id])); const totals=new Map<string,number>(); const completed=new Map<string,number>();
  for(const l of lessons){const cid=mc.get(l.module_id);if(!cid)continue;totals.set(cid,(totals.get(cid)??0)+1);if(done.has(l.id))completed.set(cid,(completed.get(cid)??0)+1)}
  const cards=base.map(c=>{const total=totals.get(c.id)??0;const finished=completed.get(c.id)??0;const pct=total?Math.round(finished/total*100):0;return {...c,totalLessons:total,completedLessons:finished,progress:pct,enrollmentStatus:em.get(c.id)??null}});if(mounted){setCourses(cards);setLoading(false)}} void load();return()=>{mounted=false}},[]);
 const filtered=useMemo(()=>courses.filter(c=>{const text=`${c.title} ${c.description??""}`.toLowerCase();if(query.trim()&&!text.includes(query.trim().toLowerCase()))return false;if(filter==="in-progress")return Boolean(c.enrollmentStatus)&&c.progress>0&&c.progress<100;if(filter==="completed")return c.progress>=100||c.enrollmentStatus==="completed";if(filter==="not-started")return !c.enrollmentStatus||c.progress===0;return true}),[courses,filter,query]);
 return <LearnShell><SectionHeader eyebrow="Courses" title="Courses" description="Explore all available learning paths and pick up exactly where you left off."/>
  <div className="learn-course-toolbar"><label className="learn-search-wrap"><Search size={17}/><input className="learn-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by course title or description" aria-label="Search courses"/></label></div>
  <div className="learn-filter-row" role="tablist" aria-label="Course filters">{([['all','All'],['in-progress','In progress'],['completed','Completed'],['not-started','Not started']] as const).map(([v,l])=><button key={v} type="button" role="tab" aria-selected={filter===v} onClick={()=>setFilter(v)} className={`learn-filter-tab ${filter===v?'active':''}`}>{l}</button>)}</div>
  {loading?<div className="learn-card p-8 text-sm">Loading your courses...</div>:dbError?<div className="learn-alert error">Unable to load your courses right now.</div>:filtered.length===0?<div className="learn-card learn-empty"><div className="mx-auto learn-icon-tile"><BookOpen size={20}/></div><h2 className="mt-5 text-xl font-bold">{courses.length?'No courses match this view':'No courses available yet'}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6">{courses.length?'Try another filter or search term.':'Your published learning paths will appear here when they are available.'}</p></div>:<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(course=>{const enrolled=Boolean(course.enrollmentStatus);const complete=course.progress>=100||course.enrollmentStatus==='completed';const started=enrolled&&course.progress>0&&!complete;const action=complete?'View course':started?'Continue':'Start learning';return <article className="learn-course-card" key={course.id}><div className="learn-course-image">{course.thumbnail_url?<img src={course.thumbnail_url} alt=""/>:<div className="learn-course-placeholder"><Sparkles size={34}/></div>}{complete&&<span className="learn-course-badge"><CheckCircle2 size={13}/> Completed</span>}</div><div className="p-5"><h2 className="mt-1 line-clamp-2 text-lg font-bold leading-6">{course.title}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5">{course.description||'Explore this practical learning path.'}</p><div className="mt-3 flex items-center gap-2 text-xs"><span>{course.totalLessons} lessons</span>{course.enrollmentStatus&&<><span>•</span><span>{course.completedLessons}/{course.totalLessons} complete</span></>}</div>{started&&<><div className="mt-4 flex items-center justify-between text-xs"><span>Progress</span><span className="font-semibold">{course.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="learn-progress-fill h-full rounded-full" style={{width:`${course.progress}%`}}/></div></>}{complete&&<div className="mt-4 flex items-center justify-between text-xs"><span className="font-semibold text-emerald-600">100% complete</span><span className="text-slate-500">Ready to review</span></div>}<Link to="/learn/courses/$slug" params={{slug:course.slug}} className="learn-course-action mt-5">{action}<ArrowRight size={16}/></Link></div></article>})}</div>}
  <div className="mt-5 flex items-center gap-2 text-xs"><Clock3 size={14}/> Course progress is based on completed lessons.</div></LearnShell>
}
