import { Linkedin, Mail, MapPin } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Reveal } from "./Reveal";
import { EMAIL, LINKEDIN_URL } from "./content";

export function Contact() {
  const [sent, setSent] = useState(false);
  return <section id="contact" className="py-24"><div className="mx-auto max-w-7xl px-5 md:px-6"><Reveal className="gradient-cta rounded-3xl p-px"><div className="rounded-[calc(var(--radius-3xl))] bg-background/95 px-6 py-12 text-center sm:px-12"><p className="eyebrow">Let's build</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Ready to Build Your AI Edge?</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Join an upcoming workshop, or book a free call to map the fastest path from where you are to shipping your first AI agent.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="mailto:coachamitsoni@gmail.com?subject=Book%20a%20Free%20Call" className="btn-base btn-cyan">Book a Free Call</a><a href={LINKEDIN_URL} target="_blank" rel="noreferrer" className="btn-base btn-outline-soft"><Linkedin className="h-4 w-4"/>Connect on LinkedIn</a></div></div></Reveal><div className="mt-12 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Reveal className="panel p-8"><h3 className="text-xl font-semibold">Let's talk</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Workshops, corporate training, speaking invitations or 1:1 coaching — send a note and I'll get back to you.</p><ul className="mt-7 space-y-4 text-sm text-muted-foreground"><li className="flex items-center gap-3"><MapPin className="h-4 w-4 text-primary"/>Noida, India</li><li className="flex items-center gap-3"><Mail className="h-4 w-4 text-primary"/><a href={`mailto:${EMAIL}`} className="hover:text-primary">{EMAIL}</a></li><li className="flex items-center gap-3"><Linkedin className="h-4 w-4 text-primary"/><a href={LINKEDIN_URL} target="_blank" rel="noreferrer" className="hover:text-primary">LinkedIn Profile</a></li></ul></Reveal><Reveal delay={100} className="panel p-8"><form className="grid gap-4 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();setSent(true);toast.success("Thanks! Your message has been noted.");}}><label className="text-sm"><span className="text-muted-foreground">Name</span><input required name="name" className="form-input mt-2" placeholder="Your name"/></label><label className="text-sm"><span className="text-muted-foreground">Email</span><input required type="email" name="email" className="form-input mt-2" placeholder="you@company.com"/></label><label className="text-sm sm:col-span-2"><span className="text-muted-foreground">What would you like help with?</span><textarea required name="message" rows={5} className="form-input mt-2 resize-none" placeholder="Tell me about your team, goals or the workshop you're interested in."/></label><button type="submit" className="btn-base btn-cyan w-full sm:w-fit sm:col-span-2">{sent ? "Message Sent" : "Send Message"}</button></form></Reveal></div></div></section>;
}

export function Footer() {
  return <footer className="border-t border-border py-10"><div className="mx-auto grid max-w-7xl gap-6 px-5 md:px-6 sm:flex sm:items-center sm:justify-between"><div><p className="font-display text-sm font-semibold">Amit Soni</p><p className="text-xs text-muted-foreground">AI Agents & Cloud Architecture Coach</p></div><div className="flex items-center gap-5 text-sm text-muted-foreground"><a href={LINKEDIN_URL} target="_blank" rel="noreferrer" className="hover:text-primary">LinkedIn</a><a href="#workshops" className="hover:text-primary">Workshops</a><a href="#courses" className="hover:text-primary">Courses</a></div><p className="text-xs text-muted-foreground">© 2026 Amit Soni. All rights reserved.</p></div></footer>;
}
