/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnCoursesRouteImport } from './routes/learn/courses'
import { Route as LearnHelpRouteImport } from './routes/learn/help'
import { Route as LearnLoginRouteImport } from './routes/learn/login'
import { Route as LearnMessagesRouteImport } from './routes/learn/messages'
import { Route as LearnNotificationsRouteImport } from './routes/learn/notifications'
import { Route as LearnProfileRouteImport } from './routes/learn/profile'
import { Route as LearnRegisterRouteImport } from './routes/learn/register'
import { Route as LearnWorkshopsRouteImport } from './routes/learn/workshops'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCoursesRoute = LearnCoursesRouteImport.update({
  id: '/learn/courses',
  path: '/learn/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnHelpRoute = LearnHelpRouteImport.update({
  id: '/learn/help',
  path: '/learn/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLoginRoute = LearnLoginRouteImport.update({
  id: '/learn/login',
  path: '/learn/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMessagesRoute = LearnMessagesRouteImport.update({
  id: '/learn/messages',
  path: '/learn/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNotificationsRoute = LearnNotificationsRouteImport.update({
  id: '/learn/notifications',
  path: '/learn/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnProfileRoute = LearnProfileRouteImport.update({
  id: '/learn/profile',
  path: '/learn/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRegisterRoute = LearnRegisterRouteImport.update({
  id: '/learn/register',
  path: '/learn/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWorkshopsRoute = LearnWorkshopsRouteImport.update({
  id: '/learn/workshops',
  path: '/learn/workshops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/courses': typeof LearnCoursesRoute
  '/learn/help': typeof LearnHelpRoute
  '/learn/login': typeof LearnLoginRoute
  '/learn/messages': typeof LearnMessagesRoute
  '/learn/notifications': typeof LearnNotificationsRoute
  '/learn/profile': typeof LearnProfileRoute
  '/learn/register': typeof LearnRegisterRoute
  '/learn/workshops': typeof LearnWorkshopsRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/courses': typeof LearnCoursesRoute
  '/learn/help': typeof LearnHelpRoute
  '/learn/login': typeof LearnLoginRoute
  '/learn/messages': typeof LearnMessagesRoute
  '/learn/notifications': typeof LearnNotificationsRoute
  '/learn/profile': typeof LearnProfileRoute
  '/learn/register': typeof LearnRegisterRoute
  '/learn/workshops': typeof LearnWorkshopsRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/courses': typeof LearnCoursesRoute
  '/learn/help': typeof LearnHelpRoute
  '/learn/login': typeof LearnLoginRoute
  '/learn/messages': typeof LearnMessagesRoute
  '/learn/notifications': typeof LearnNotificationsRoute
  '/learn/profile': typeof LearnProfileRoute
  '/learn/register': typeof LearnRegisterRoute
  '/learn/workshops': typeof LearnWorkshopsRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn/courses'
    | '/learn/help'
    | '/learn/login'
    | '/learn/messages'
    | '/learn/notifications'
    | '/learn/profile'
    | '/learn/register'
    | '/learn/workshops'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn/courses'
    | '/learn/help'
    | '/learn/login'
    | '/learn/messages'
    | '/learn/notifications'
    | '/learn/profile'
    | '/learn/register'
    | '/learn/workshops'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/learn/courses'
    | '/learn/help'
    | '/learn/login'
    | '/learn/messages'
    | '/learn/notifications'
    | '/learn/profile'
    | '/learn/register'
    | '/learn/workshops'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnCoursesRoute: typeof LearnCoursesRoute
  LearnHelpRoute: typeof LearnHelpRoute
  LearnLoginRoute: typeof LearnLoginRoute
  LearnMessagesRoute: typeof LearnMessagesRoute
  LearnNotificationsRoute: typeof LearnNotificationsRoute
  LearnProfileRoute: typeof LearnProfileRoute
  LearnRegisterRoute: typeof LearnRegisterRoute
  LearnWorkshopsRoute: typeof LearnWorkshopsRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/courses': {
      id: '/learn/courses'
      path: '/learn/courses'
      fullPath: '/learn/courses'
      preLoaderRoute: typeof LearnCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/help': {
      id: '/learn/help'
      path: '/learn/help'
      fullPath: '/learn/help'
      preLoaderRoute: typeof LearnHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/login': {
      id: '/learn/login'
      path: '/learn/login'
      fullPath: '/learn/login'
      preLoaderRoute: typeof LearnLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/messages': {
      id: '/learn/messages'
      path: '/learn/messages'
      fullPath: '/learn/messages'
      preLoaderRoute: typeof LearnMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/notifications': {
      id: '/learn/notifications'
      path: '/learn/notifications'
      fullPath: '/learn/notifications'
      preLoaderRoute: typeof LearnNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/profile': {
      id: '/learn/profile'
      path: '/learn/profile'
      fullPath: '/learn/profile'
      preLoaderRoute: typeof LearnProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/register': {
      id: '/learn/register'
      path: '/learn/register'
      fullPath: '/learn/register'
      preLoaderRoute: typeof LearnRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/workshops': {
      id: '/learn/workshops'
      path: '/learn/workshops'
      fullPath: '/learn/workshops'
      preLoaderRoute: typeof LearnWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnCoursesRoute: LearnCoursesRoute,
  LearnHelpRoute: LearnHelpRoute,
  LearnLoginRoute: LearnLoginRoute,
  LearnMessagesRoute: LearnMessagesRoute,
  LearnNotificationsRoute: LearnNotificationsRoute,
  LearnProfileRoute: LearnProfileRoute,
  LearnRegisterRoute: LearnRegisterRoute,
  LearnWorkshopsRoute: LearnWorkshopsRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
